-- 002_types.sql
CREATE TYPE user_role AS ENUM (
    'MP',
    'DISTRICT_AUTHORITY',
    'IMPLEMENTING_AGENCY',
    'MONITORING_OFFICER',
    'MINISTRY',
    'ADMIN',
    'PUBLIC'
);

CREATE TYPE project_status AS ENUM (
    'RECOMMENDED',
    'UNDER_REVIEW',
    'CLARIFICATION_REQUIRED',
    'SANCTIONED',
    'REJECTED',
    'ASSIGNED',
    'IN_PROGRESS',
    'VERIFICATION_PENDING',
    'VERIFIED',
    'COMPLETED',
    'CLOSED'
);

CREATE TYPE verification_priority AS ENUM (
    'NORMAL',
    'ATTENTION',
    'HIGH_PRIORITY'
);

CREATE TYPE evidence_type AS ENUM (
    'SANCTION_DOCUMENT',
    'ESTIMATE_DOCUMENT',
    'WORK_ORDER',
    'PROGRESS_PHOTOGRAPH',
    'COMPLETION_PHOTOGRAPH',
    'INSPECTION_PHOTOGRAPH',
    'INSPECTION_REPORT',
    'EXPENDITURE_DOCUMENT',
    'COMPLETION_CERTIFICATE',
    'SUPPORTING_RECORD',
    'LOCATION_EVIDENCE'
);

CREATE TYPE alert_status AS ENUM (
    'OPEN',
    'IN_REVIEW',
    'ESCALATED',
    'RESOLVED'
);
